# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/sumire/Documents/Unreal Engine/5.3.0
GAMEPROJECTFILE =/home/sumire/Documents/Unreal Projects/Mayajala/Mayajala.uproject

TARGETS = \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	Mayajala-Linux-DebugGame  \
	Mayajala-Linux-Shipping  \
	Mayajala \
	MayajalaEditor-Linux-DebugGame  \
	MayajalaEditor-Linux-Shipping  \
	MayajalaEditor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend MayajalaEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug MayajalaEditor-Linux-Debug


UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

Mayajala-Linux-DebugGame:
	 $(PROJECTBUILD) Mayajala Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Mayajala-Linux-Shipping:
	 $(PROJECTBUILD) Mayajala Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Mayajala:
	 $(PROJECTBUILD) Mayajala Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

MayajalaEditor-Linux-DebugGame:
	 $(PROJECTBUILD) MayajalaEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

MayajalaEditor-Linux-Shipping:
	 $(PROJECTBUILD) MayajalaEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

MayajalaEditor:
	 $(PROJECTBUILD) MayajalaEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
